### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by remi-braun**
- creating a proper package containing providers.yml + updates in setup.py
- adding exceptions
- some refactoring and bug corrections
- updates in providers.yml in order to access more parameters

### CODE REVIEW

**Comment by sbrunato** [comment]
Hi Remi, thanks for the PR, can you make a `git rebase` on your branch to include the last updates ? This would help us to review before merging. Thanks!

**Comment by remi-braun** [comment]
I am not very familiar with this, I did a `git rebase master` and resolved the conflicts but seemed not to have change anything...
Sorry for all this  I am quite a newbie when updating opensource libs

Should I rebase on the develop branch ? Because it tells me I am already up to date.

**Comment by sbrunato** [comment]
No problem, check that you have a remote pointing on https://github.com/CS-SI/eodag-sentinelsat:
```sh
git remote -v

upstream	git@github.com:CS-SI/eodag-sentinelsat.git (fetch)
upstream	git@github.com:CS-SI/eodag-sentinelsat.git (push)
```
If not, add it: 
```sh
git remote add upstream git@github.com:CS-SI/eodag-sentinelsat.git
```
And then:
```sh
git fetch upstream
git checkout your-local-branch
git rebase upstream/develop
```

**Comment by remi-braun** [comment]
I have an access issue:
```
> git fetch upstream
The authenticity of host 'github.com (140.82.121.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.3' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

I have the remote pointing enabled, if I do it again it prints:
```
> git remote add upstream git@github.com:CS-SI/eodag-sentinelsat.git
fatal: remote upstream already exists.
```

**Comment by sbrunato** [comment]
yes, sorry to be able to use `git@github.com:CS-SI/eodag-sentinelsat.git` you have to set a ssh key in github settings.
You can use instead as remote :
```sh
git remote add upstream https://github.com/CS-SI/eodag-sentinelsat.git

git fetch upstream

git checkout your-develop-branch
# rebase on upstream/develop branch, move your local commits after upstream latest commits
git rebase upstream/develop
```

**Comment by remi-braun** [comment]
Ok I did that, did it changed something ? Is everything OK ?

**Comment by sbrunato** [comment]
> Ok I did that, did it changed something ? Is everything OK ?

yes, thanks!

**Review by sbrunato — APPROVED** [review]

**Pull request merged**
